# Generated by Django 3.0.5 on 2025-03-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20250315_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectivequestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjective_questions', to='exam.Course'),
        ),
    ]
