# Generated by Django 3.0.5 on 2025-04-04 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20250404_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='course',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
