# Generated by Django 3.0.5 on 2025-04-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20250404_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mcq', models.IntegerField(default=0)),
                ('num_subjective', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Course')),
            ],
        ),
    ]
