# Generated by Django 3.0.5 on 2025-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_subjectivequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
